language: node_js

script:
  - npm run build
  - npm run test
  - npm run upload-build

addons:
  apt:
    packages:
      - libudev-dev

matrix:
  include:
    - os: linux
      dist: xenial
      node_js: "11.5.0"
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt update
        - sudo apt-get install -y gcc-8 g++-8
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60
    - os: osx
      osx_image: xcode10.1
      node_js: "11.5.0"
    - os: linux
      dist: xenial
      node_js: "12.4.0"
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update
        - sudo apt-get install -y gcc-8 g++-8
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60
    - os: osx
      osx_image: xcode10.1
      node_js: "12.4.0"
