# This workflow will run build the typescript source files, run linter and prettier
name: CI Check

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'
  # schedule:
    # Trigger workflow run every workday (Mon-Fri) at 0700
    # - cron:  '0 7 * * 1,2,3,4,5'

jobs:
  build:
    name: "Build & Test"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-18.04,
          macos-latest,
          windows-latest
        ]
        node-version: [
          11,
          12,
          14,
          16
        ]
    env:
      AZURE_CONTAINER: ${{ secrets.AZURE_CONTAINER }}
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}

    steps:
      - name: Set git to use LF
        if: matrix.os == 'windows-latest'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout repo and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Pre-Install hook Ubuntu"
        if: matrix.os == 'ubuntu-18.04'
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y gcc-8 g++-8
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60
          sudo apt install libudev-dev

      - name: "Install python2.7 on windows"
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: "Install dependencies"
        run: npm ci

      - name: "Check for linting issues"
        run: npm run tslint

      - name: "Check for prettier issues"
        run: npm run prettier-check

      - name: "Build library"
        run: npm run build

      - name: "Run unt tests"
        run: npm run test

      - name: "Check for dependency vulnerabilities"
        run: npm run audit-check

  slack-notify:
    name: "Notify Failure"
    runs-on: ubuntu-latest
    needs: [ build ]
    if: always() && (needs.build.result == 'failure') && (github.ref == 'refs/heads/master')
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: sdk
          SLACK_COLOR: "#ff5050"
          SLACK_ICON: https://www.huddly.com/content/uploads/2018/10/huddly-logo-white-300x300.png?size=48
          SLACK_MESSAGE: 'device-api-usb pipeline failed on master! Attention needed.'
          SLACK_TITLE: Build Failed!
          SLACK_USERNAME: "Github Actions"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
